import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import{Wallet,Send,PlusCircle,ArrowDownToLine,ArrowUpRight,History,LogOut,Eye,EyeOff,ShieldCheck,Users,BarChart3}from"lucide-react";import"./index.css";

const money=n=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN"}).format(n);
const seed={users:[{id:"u1",name:"Demo User",email:"demo@quickpay.test",password:"demo1234",pin:"1234",role:"admin",balance:25000}],tx:[{id:1,user:"u1",type:"funding",amount:25000,status:"success",note:"Demo opening balance",date:new Date().toISOString()}]};
function load(){try{return JSON.parse(localStorage.qpdb)||seed}catch{return seed}}
function save(d){localStorage.qpdb=JSON.stringify(d)}
function Auth({onLogin}){const[m,setM]=useState("login"),[f,setF]=useState({name:"",email:"demo@quickpay.test",password:"demo1234"}),[err,setErr]=useState("");
function submit(e){e.preventDefault();let d=load();if(m==="register"){if(d.users.some(u=>u.email===f.email.toLowerCase()))return setErr("Email already exists");let u={id:"u"+Date.now(),name:f.name,email:f.email.toLowerCase(),password:f.password,pin:null,role:"user",balance:0};d.users.push(u);save(d);onLogin(u)}else{let u=d.users.find(x=>x.email===f.email.toLowerCase()&&x.password===f.password);if(!u)return setErr("Invalid login. Try demo@quickpay.test / demo1234");onLogin(u)}}return <div className="min-h-screen flex items-center justify-center bg-slate-950 px-4"><form onSubmit={submit} className="w-full max-w-md bg-white rounded-3xl p-8 shadow-2xl"><div className="w-12 h-12 rounded-2xl bg-indigo-600 text-white flex items-center justify-center mb-5"><Wallet/></div><h1 className="text-3xl font-black">QuickPay</h1><p className="text-slate-500 mt-1 mb-7">Mini fintech wallet — demonstration edition</p>{m==="register"&&<input required placeholder="Full name" className="w-full border rounded-xl p-3 mb-3" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input required type="email" placeholder="Email" className="w-full border rounded-xl p-3 mb-3" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password" className="w-full border rounded-xl p-3 mb-3" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{err&&<div className="bg-red-50 text-red-700 p-3 rounded-xl text-sm mb-3">{err}</div>}<button className="w-full bg-indigo-600 text-white rounded-xl p-3 font-bold">{m==="login"?"Log in":"Create account"}</button><button type="button" onClick={()=>{setM(m==="login"?"register":"login");setErr("")}} className="w-full mt-4 text-indigo-600 text-sm">{m==="login"?"Create an account":"Back to login"}</button></form></div>}
function App(){const[user,setUser]=useState(()=>JSON.parse(localStorage.qpuser||"null"));const[tab,setTab]=useState("home");const[db,setDb]=useState(load());const[hide,setHide]=useState(false);const[modal,setModal]=useState(null);const[form,setForm]=useState({});const[msg,setMsg]=useState("");
useEffect(()=>save(db),[db]);
if(!user)return <Auth onLogin={u=>{localStorage.qpuser=JSON.stringify(u);setUser(u)}}/>;
const me=db.users.find(u=>u.id===user.id)||user;const tx=db.tx.filter(t=>t.user===me.id);
function logout(){localStorage.removeItem("qpuser");setUser(null)}
function action(type){let amount=Number(form.amount||0);if(amount<=0)return setMsg("Enter a valid amount.");let d=structuredClone(db);
if(type==="fund"){d.users.find(u=>u.id===me.id).balance+=amount;d.tx.unshift({id:Date.now(),user:me.id,type:"funding",amount,status:"success",note:"Demo wallet funding",date:new Date().toISOString()})}
if(type==="send"){let r=d.users.find(u=>u.email===String(form.email||"").toLowerCase());if(!r)return setMsg("Recipient not found.");if(r.id===me.id)return setMsg("Choose another user.");if(form.pin!=="1234"&&form.pin!==me.pin)return setMsg("Incorrect PIN.");if(me.balance<amount)return setMsg("Insufficient balance.");me.balance-=amount;r.balance+=amount;d.tx.unshift({id:Date.now(),user:me.id,type:"transfer_out",amount,status:"success",note:"Transfer to "+r.email,date:new Date().toISOString()});d.tx.unshift({id:Date.now()+1,user:r.id,type:"transfer_in",amount,status:"success",note:"Transfer received",date:new Date().toISOString()})}
if(type==="withdraw"){if(form.pin!=="1234"&&form.pin!==me.pin)return setMsg("Incorrect PIN.");if(me.balance<amount)return setMsg("Insufficient balance.");me.balance-=amount;d.tx.unshift({id:Date.now(),user:me.id,type:"withdrawal",amount,status:"pending",note:"Demo bank withdrawal",date:new Date().toISOString()})}
if(type==="pin"){if(!/^\d{4}$/.test(form.pin||""))return setMsg("PIN must be 4 digits.");me.pin=form.pin}
setDb(d);setForm({});setModal(null);setMsg(type==="fund"?"Wallet funded successfully (demo mode).":type==="send"?"Transfer successful (demo mode).":type==="withdraw"?"Withdrawal submitted (demo mode).":"PIN saved.");}
function setDb(d){save(d);setDbState(d)}
const[_,setDbState]=useState(0);
function refresh(){setDbState(x=>x+1);setDb(load())}
const current=load().users.find(u=>u.id===me.id)||me;const history=load().tx.filter(t=>t.user===me.id);
return <div className="min-h-screen"><header className="bg-white border-b sticky top-0 z-10"><div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center"><div className="flex items-center gap-2 font-black text-xl"><span className="bg-indigo-600 text-white rounded-xl p-2"><Wallet size={20}/></span>QuickPay</div><div className="flex items-center gap-4"><div className="hidden sm:block text-right"><b>{current.name}</b><div className="text-xs text-slate-500">{current.email}</div></div><button onClick={logout} className="border rounded-xl p-2"><LogOut size={18}/></button></div></div></header>
<main className="max-w-6xl mx-auto px-4 py-7"><div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 text-sm text-amber-900 mb-6"><b>Demo mode:</b> payments and withdrawals are simulated locally. No bank or Paystack account is connected.</div>{msg&&<div className="bg-indigo-50 text-indigo-800 rounded-xl p-3 mb-5 text-sm">{msg}<button onClick={()=>setMsg("")} className="float-right font-bold">×</button></div>}
<div className="bg-gradient-to-br from-indigo-700 to-violet-600 text-white rounded-3xl p-7 shadow-xl"><div className="text-indigo-100 text-sm">Available balance</div><div className="flex items-center gap-3 text-4xl font-black mt-2">{hide?"••••••":money(current.balance)}<button onClick={()=>setHide(!hide)}>{hide?<Eye/>:<EyeOff/>}</button></div><div className="text-indigo-100 mt-4 text-sm">NGN wallet · Demo account</div></div>
<div className="grid md:grid-cols-4 gap-4 mt-5">{[["Fund wallet",PlusCircle,"fund"],["Send money",Send,"send"],["Withdraw",ArrowDownToLine,"withdraw"],["Set PIN",ShieldCheck,"pin"]].map(([n,I,k])=><button key={k} onClick={()=>{setForm({});setModal(k)}} className="bg-white rounded-2xl p-5 shadow-sm text-left hover:shadow-md"><I className="text-indigo-600 mb-3"/><b>{n}</b><div className="text-xs text-slate-500 mt-1">Open action</div></button>)}</div>
<div className="bg-white rounded-3xl mt-6 p-6 shadow-sm"><div className="flex justify-between items-center mb-4"><h2 className="text-xl font-black flex gap-2 items-center"><History/>Transaction history</h2><button onClick={refresh} className="text-indigo-600 text-sm">Refresh</button></div>{history.length===0?<p className="text-slate-500 py-8 text-center">No transactions yet.</p>:history.map(t=><div key={t.id} className="flex justify-between py-4 border-b last:border-0"><div className="flex gap-3 items-center"><span className="p-2 rounded-xl bg-slate-100">{t.type==="transfer_out"||t.type==="withdrawal"?<ArrowUpRight size={18}/>:<ArrowDownToLine size={18}/>}</span><div><b>{t.note}</b><div className="text-xs text-slate-500">{new Date(t.date).toLocaleString()} · {t.status}</div></div></div><b className={t.type==="funding"||t.type==="transfer_in"?"text-emerald-600":""}>{t.type==="funding"||t.type==="transfer_in"?"+":"-"}{money(t.amount)}</b></div>)}</div>
<div className="grid md:grid-cols-3 gap-4 mt-6"><Info icon={ShieldCheck} title="PIN security" text="4-digit authorization is demonstrated locally."/><Info icon={Users} title="Transfers" text="Send demo funds to another registered user."/><Info icon={BarChart3} title="Admin-ready" text="Transaction data is structured for a future admin dashboard."/></div></main>
{modal&&<Modal title={modal==="fund"?"Fund Wallet":modal==="send"?"Send Money":modal==="withdraw"?"Withdraw":"Set Transaction PIN"} close={()=>setModal(null)}>{modal==="fund"&&<><input type="number" placeholder="Amount ₦" className="field" value={form.amount||""} onChange={e=>setForm({...form,amount:e.target.value})}/><button className="primary" onClick={()=>action("fund")}>Simulate payment</button></>}{modal==="send"&&<><input type="email" placeholder="Recipient email" className="field" value={form.email||""} onChange={e=>setForm({...form,email:e.target.value})}/><input type="number" placeholder="Amount ₦" className="field" value={form.amount||""} onChange={e=>setForm({...form,amount:e.target.value})}/><input maxLength="4" placeholder="4-digit PIN (demo: 1234)" className="field" value={form.pin||""} onChange={e=>setForm({...form,pin:e.target.value})}/><button className="primary" onClick={()=>action("send")}>Transfer</button></>}{modal==="withdraw"&&<><input type="number" placeholder="Amount ₦" className="field" value={form.amount||""} onChange={e=>setForm({...form,amount:e.target.value})}/><input placeholder="Bank / account details (demo)" className="field" value={form.bank||""} onChange={e=>setForm({...form,bank:e.target.value})}/><input maxLength="4" placeholder="4-digit PIN (demo: 1234)" className="field" value={form.pin||""} onChange={e=>setForm({...form,pin:e.target.value})}/><button className="primary" onClick={()=>action("withdraw")}>Submit withdrawal</button></>}{modal==="pin"&&<><input maxLength="4" inputMode="numeric" placeholder="New 4-digit PIN" className="field" value={form.pin||""} onChange={e=>setForm({...form,pin:e.target.value})}/><button className="primary" onClick={()=>action("pin")}>Save PIN</button></>}</Modal>}</div>}
function Info({icon:I,title,text}){return <div className="bg-white rounded-2xl p-5 shadow-sm"><I className="text-indigo-600 mb-3"/><b>{title}</b><p className="text-sm text-slate-500 mt-1">{text}</p></div>}
function Modal({title,close,children}){return <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-30"><div className="bg-white rounded-3xl p-6 w-full max-w-md"><div className="flex justify-between mb-5"><h2 className="text-xl font-black">{title}</h2><button onClick={close}>×</button></div>{children}</div></div>}
export default App;
